name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Setup npm
        run: npm install

      - name: Build documentation
        run: |
          npm run docs
          docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build

      - name: Sync GitHub Wiki
        uses: spenserblack/actions-wiki@main
        with:
          path: docs
